spring.application.name=URL-Shortening

spring.datasource.url=jdbc:postgresql://localhost:5432/url_shortening_db
spring.datasource.username=postgres
spring.datasource.password=Temp@123456

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

app-jwt-expiration-milliseconds=604800000

app-jwt-secret=25873f24da142a06a15bdb84fad1df0b198180734d0045653abce7591c8e4881

