spring.application.name=URL-Shortening

spring.datasource.url=jdbc:postgresql://localhost:5432/url_shortening_db
spring.datasource.username=postgres
spring.datasource.password=Temp@123456

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
